# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/ctyano/certui"
  version "0.0.17"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ctyano/certui/releases/download/v0.0.17/certui_0.0.17_darwin_arm64.zip"
      sha256 "703f27f62d6f400c207031deed34302b55b6d4530bf9a2a6a812fda13537c4aa"

      def install
        bin.install "certui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ctyano/certui/releases/download/v0.0.17/certui_0.0.17_darwin_amd64.zip"
      sha256 "d25e3ceff62e094a488134bd234b309106956f68ecd1e55772de769262025ed6"

      def install
        bin.install "certui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ctyano/certui/releases/download/v0.0.17/certui_0.0.17_linux_arm64.zip"
      sha256 "1fbecb90abcf495dd597746470b771091220502da7355cc335a5ed2ba11be0c7"

      def install
        bin.install "certui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ctyano/certui/releases/download/v0.0.17/certui_0.0.17_linux_amd64.zip"
      sha256 "3a2d731e4bc2afc1bdf4042eab4eb5ecc9b0e04b22b956d6fb7b09c26ae27969"

      def install
        bin.install "certui"
      end
    end
  end

  test do
    system "#{bin}/certui version"
  end
end
